language: node_js
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
before_script:
  - npm run test -- --silent --noStackTrace
  - npm run lint
script:
  - npm run build
after_script:
  - npm run test:coverage
  - npm run test:coverage:report
after_success:
  # to make the build work through rollup with DID logic (https://github.com/blockchain-certificates/cert-verifier-js/pull/1257)
  # we are aliasing readable-stream to https://github.com/exogee-technology/readable-stream
  # however this breaks semantic release because the shape of the export is different
  # so we install the regular version of readable stream to enable expected use by semantic release
  # it is an inelegant patch but it's a quick solution to the problem and is acceptable as it is the last step of the CI
  - npm uninstall readable-stream
  - rm -rf ./node_modules
  - rm package-lock.json
  - npm i --legacy-peer-deps
  - npm install readable-stream --legacy-peer-deps
  - npm run semantic-release
